### ISSUE TITLE
SpvModuleScopeVarParserTest_Builtin* tests have invalid SPIR-V

### ISSUE THREAD

**Issue by jenatali** [dneto0/spirv-samples#2]
These tests declare things like:
```
OpMemberDecorate %_struct_10 0 BuiltIn Position
OpMemberDecorate %_struct_10 1 BuiltIn PointSize
OpMemberDecorate %_struct_10 2 BuiltIn ClipDistance
OpMemberDecorate %_struct_10 3 BuiltIn CullDistance
%float = OpTypeFloat 32
%v4float = OpTypeVector %float 4
%uint_1 = OpConstant %uint 1
%_arr_float_uint_1 = OpTypeArray %float %uint_1
%_struct_10 = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
%_ptr_Output__struct_10 = OpTypePointer Output %_struct_10
```

However, `%_struct_10` was not decorated as `Block`, which (I believe) makes it invalid to decorates its members as built-in. At least, according the [Vulkan spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap15.html#interfaces-iointerfaces-builtin) this seems to be the case:
> be declared in a block whose top-level members are the built-ins.

I couldn't find explicit rules in the core SPIR-V spec for this, however.

**Comment by gfxstrand** [comment]
We likely should add a spec VU.  Maybe something like

> If a struct type has a member decorated with `BuiltIn`, it **must** be decorated with `Block`

or something like that.  But I'm pretty sure the spec intent is clear.

**Comment by dneto0** [comment]
On the registry issue I acknowledged these are invalid examples. I'll update them to decorate the struct with Block.

**Comment by dneto0** [comment]
Fix upstream is https://dawn-review.googlesource.com/c/tint/+/73241 
It turns out there were only two examples that needed patching.

I implemented the check in the validator. https://github.com/KhronosGroup/SPIRV-Tools/pull/4665

**Comment by jenatali** [comment]
Looks like one test got missed: https://github.com/dneto0/spirv-samples/blob/main/spvasm/SpvModuleScopeVarParserTest_BuiltinPosition_StorePosition_PerVertexStructOutOfOrderDecl.spvasm#L10
